#!/usr/bin/env bash
# transfers a file from our client to a server
# en el IF verifica que si tenga los 3 parametros
# en el else con el [i] para no poder password
if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
fi
