#!/usr/bin/env bash
# install NginX at web-server
# la y es para darle yes 
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
