#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#!/usr/bin/env bash
# install nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart