#!/usr/bin/env bash
# install load balancer
sudo apt install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_original
sudo sed -i "$ a frontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 2871-web-01 34.74.231.223:80 check\n\tserver 2871-web-02 54.226.230.158:80 check" /etc/haproxy/haproxy.cfg
sudo cp /etc/default/haproxy /etc/default/haproxy_original
sudo sed -i "$ a ENABLED=1" /etc/default/haproxy
sudo service haproxy start
