#!/usr/bin/env bash
# Write a Bash script that:
# Creates the file /var/run/holbertonscript.pid containing its PID
echo $$ > /var/run/holbertonscript.pid
trap "I hate the kill command && /var/run/holbertonscript.pid " SIGTERM
trap "Y U no love me?!" SIGINT
while true
do
	trap "echo To infinity and beyond"
done
