#!/usr/bin/env bash
# Write a Bash script that:
# Creates the file /var/run/holbertonscript.pid containing its PID
echo $$ > /var/run/holbertonscript.pid
trap "echo I hate the kill command && sudo rm /var/run/holbertonscript.pid " SIGTERM
trap "echo Y U no love me?!" SIGINT
while true
do
	echo "To infinity and beyond"
done
