#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with while
iterador=1
while ((iterador<=10))
do
	if ((iterador == 4)); then
		echo "bad luck"
	elif ((iterador == 8)); then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((iterador++))
done
