#!/usr/bin/env bash
# Write a Bash script that displays: The content of the current directory
var="holbertonschool"
if [ -e $var ]; then
	echo "holbertonschool file exists"
	if [ -s $var ]; then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f $var ]; then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
