#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.cpy
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/host.copy
echo "8.8.8.8 facebook.com" > /etc/host
cp -f ~/hosts.cpy /etc/hosts
